#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org
START=99
USE_PROCD=1

append_bool() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _val
	config_get_bool _val "$section" "$option" '0'
	[ "$_val" -gt 0 ] && append args "$3"
}

append_string() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _val
	config_get _val "$section" "$option"
	[ -n "$_val" ] && append args "$3$_val"
}

start_service() {
	config_load "p910nd"
	config_foreach start_p910nd p910nd
}


start_p910nd() {
	local section="$1" runas_root
	config_get_bool "enabled" "$section" "enabled" '1'
	if [ "$enabled" -gt 0 ]; then
		args="-d " # runs in foreground & prints log messages to stdout
		config_get port "$section" port
		name=p910${port}d
		append_bool "$section" bidirectional "-b"
		append_string "$section" device "-f "
		append_string "$section" bind "-i "
		append_string "$section" port ""
		procd_open_instance $name
		procd_set_param command /usr/sbin/p910nd $args
		procd_set_param respawn

		config_get_bool runas_root "$section" runas_root 0
		[ "$runas_root" -ne 1 ] && procd_set_param user p910nd

		config_get_bool "mdns" "$section" "mdns" '0'
		config_get mdns_note "$section" mdns_note
		config_get mdns_ty "$section" mdns_ty
		config_get mdns_product "$section" mdns_product
		config_get mdns_mfg "$section" mdns_mfg
		config_get mdns_mdl "$section" mdns_mdl
		config_get mdns_cmd "$section" mdns_cmd
		[ "$mdns" -gt 0 ] && procd_add_mdns "pdl-datastream" "tcp" "$((port+9100))" "note=$mdns_note" "ty=$mdns_ty" "product=$mdns_product" "usb_MFG=$mdns_mfg" "usb_MDL=$mdns_mdl" "usb_CMD=$mdns_cmd"
		
		procd_set_param stdout 1 # relay stdout to logd
		procd_set_param stderr 1 # relay stderr to logd

		procd_close_instance
	fi
}

# src: https://man.cx/p910nd
# NAME
#   p910nd − port 9100+n printer daemon
# 
# SYNOPSIS
#   p910nd [-f device] [-i bindaddr] [-bvd] [0|1|2]
# 
# DESCRIPTION
#   p910nd is a small daemon that copies any data received on the port it is listening on to the corresponding printer port. Port 9100 is copied to /dev/lp0, 9101 to /dev/lp1 and 9102 to /dev/lp2. The default is port 9100 to /dev/lp0.
# 
#   -f option, to specify a different printer device, e.g. /dev/usblp0.
#   -i option, to specify binding to one address instead of all interfaces which is the default.
#   -b option turns on bidirectional copying.
#   -v option shows the version number.
#   -d option causes the daemon to run in the foreground in standalone mode and prints log messages to stdout for debugging.
